[package]
name = "m3u8-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
image = "0.25.6"
reqwest = { version = "0.12.15", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
regex = "1.5.4"
md5 = "0.7.0"
rfd = "0.15.3"
